name: CI Library Components & Main App Deploy

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'PopupsProvider/**'
      - 'apps/main-app/**'  # Solo afecta a los cambios en 'main-app'
  pull_request:
    branches:
      - dev
    paths:
      - 'PopupsProvider/**'

permissions:
  contents: read
  actions: read

jobs:
  test-components:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'  # Solo ejecuta para la rama dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Jest tests
        run: npm test
        env:
          CI: true

      - name: Run sui-mono tasks
        run: npx sui-mono check

      - name: Lint code
        run: npm run lint

  deploy-main-app:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Solo ejecuta para la rama main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Check if main-app was affected
        id: affected
        run: |
          npx nx affected --target=build --base=origin/main --projects=main-app || echo "false" > affected.txt
          if grep -Fxq "false" affected.txt; then
            echo "No changes in main-app"
            exit 0
          else
            echo "Changes detected in main-app"
          fi
        shell: bash

      - name: Deploy to Vercel
        if: steps.affected.outcome == 'success'
        run: |
          npm install -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
